name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: action
            steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install aria2 -y
        python -m pip install --upgrade pip

        pip install yt-dlp
    
